version: 2.1

jobs:
  linux-build-and-test:
    machine:
      image: ubuntu-2404:current
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'sudo apt-get update && sudo apt-get install -y && sudo rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing GCC
          command: 'sudo apt-get update && sudo apt-get install -y g++'
      #- run:
      #
      # For some reason, installing valgrind stalls.
      # This step is using up all my credits in CircleCI.
      # So I'm disabling the valgrind tests for now.  -Andrew 2025-2-17
      #
      #    name: Installing valgrind
      #    command: 'sudo apt-get update && sudo apt-get install -y valgrind'
      - run:
          name: Build
          command: |
            # Retrieve the code for the "jacobi_pd" submodule dependency.
            git submodule init
            git submodule update
            # Now try compiling the code.
            cd tests
            g++ -g -O0 -coverage -fno-inline -fno-inline-small-functions -fno-default-inline -I../include -I../jacobi_pd/include -o test_superpose3d test_superpose3d.cpp
            cd ..
      - run:
          name: Test
          command: |
            cd tests
            ./test_superpose3d 4 1000
            ./test_superpose3d 10 1000
            ./test_superpose3d 100 1000
            ./test_superpose3d 1000 1000
            ./test_superpose3d 10000 100
            ./test_superpose3d 100000 10
            # Recompile with debug flags enabled.
            g++ -g -O0 -I../include -I../jacobi_pd/include -o test_superpose3d test_superpose3d.cpp
            # Now use valgrind to find memory leaks and other errors:
            ### Disabling the valgrind tests for now.  See comment above.
            ### valgrind --leak-check=yes --error-exitcode=1 ./test_superpose3d 10 10
            ./test_superpose3d 10 10
            bash <(curl -s https://codecov.io/bash)
            cd ..

workflows:
  main:
    jobs:
      - linux-build-and-test
